PROGRAM areaOfRectangularCube
    IMPLICIT NONE
    REAL::A,B,C,AREA
    PRINT*,"ENTER THE VALUE OF A:"
    READ*,A
    PRINT*,"ENTER THE VALUE OF B:"
    READ*,B
    PRINT*,"ENTER THE VALUE OF C:"
    READ*,C
    AREA=2*(A*B+B*C+C*A)
    PRINT*,"THE AREA OF THE RECTANGLE IS:", AREA
END PROGRAM
