PROGRAM diagonalOfRectangularCube
    IMPLICIT NONE
    REAL::A,B,C,D
    PRINT*,"ENTER THE VALUE OF A:"
    READ*,A
    PRINT*,"ENTER THE VALUE OF B:"
    READ*,B
    PRINT*,"ENTER THE VALUE OF C:"
    READ*,C
    D=SQRT(A**2+B**2+C**2)
    PRINT*,"THE DIAGONAL LENGTH OF THE RECTANGULAR CUBE IS:", D
END PROGRAM

