PROGRAM volumeOfRectangularCube
    IMPLICIT NONE
    REAL::A,B,C,V
    PRINT*,"ENTER THE VALUE OF A:"
    READ*,A
    PRINT*,"ENTER THE VALUE OF B:"
    READ*,B
    PRINT*,"ENTER THE VALUE OF C:"
    READ*,C
    V=A*B*C
    PRINT*,"THE VOLUME OF THE RECTANGULAR CUBE IS:", V
END PROGRAM
