PROGRAM CircumferenceOfCircle
    IMPLICIT NONE
    REAL:: PHI,R,C;
    PHI=3.1416;
    PRINT*,"ENTER THE VALUE OF RADIUS(R)"
    READ*,R;
    C=2*PHI*R;
    PRINT*,"THE CIRCUMFERENCE OF CIRCLE IS:", C;
END PROGRAM
