PROGRAM areaOfParallelogram
    IMPLICIT NONE
    REAL::B,H,AREA
    PRINT*,"ENTER THE VALUE OF BASE(b):"
    READ*,B
    PRINT*,"ENTER THE VALUE OF HEIGHT(h):"
    READ*,H
    AREA=B*H
    PRINT*,"THE AREA OF THE PARALLELOGRAM IS:", AREA
END PROGRAM
