PROGRAM perimeterOfParallelogram
    IMPLICIT NONE
    REAL::A,B,P
    PRINT*,"ENTER THE VALUE OF ONE SIDE(a):"
    READ*,A
    PRINT*,"ENTER THE VALUE OF ANOTHER SIDE(b):"
    READ*,B
    P=2*(A+B)
    PRINT*,"THE PERIMETER OF THE PARALLELOGRAM IS:",P
END PROGRAM
