PROGRAM areaOfSphere
    IMPLICIT NONE
    REAL:: PHI, R, AREA
    PHI=3.1416
    PRINT*,"ENTER THE VALUE OF RADIUS(r):"
    READ*,R
    AREA=4*PHI*R**2
    PRINT*,"AREA OF THE SPHERE:", AREA
END PROGRAM
