PROGRAM fahrenheitToKelvin
    IMPLICIT NONE
    REAL::F,K
    PRINT*,"ENTER THE VALUE OF FAHRENHEIT SCALE:"
    READ*,F;
    K= (5*F-160)/9+273;
    PRINT*, "THE VALUE IN Kelvin SCALE:",K
END PROGRAM
