PROGRAM KelvinToFahrenheit
    IMPLICIT NONE
    REAL::F,K
    PRINT*,"ENTER THE VALUE OF KELVIN SCALE:"
    READ*,K;
    F= (9*k-2457)/5+32;
    PRINT*, "THE VALUE IN FAHRENHEIT SCALE:",F
END PROGRAM

