PROGRAM areaOfEquilateralTriangle
    REAL::A,AREA
    PRINT*,"INPUT THE VALUE OF SIDE(a):"
    READ*, A
    AREA=(SQRT(3.0)*A**2)/4
    PRINT*,"THE AREA OF THE EQUILATERAL TRIANGLE IS:",AREA

END PROGRAM
