PROGRAM AreaOfCircle
    IMPLICIT NONE
    REAL:: PHI,R,AREA;
    PHI=3.1416;
    PRINT*,"ENTER THE VALUE OF RADIUS(R)"
    READ*,R;
    AREA=PHI*R**2;
    PRINT*,"THE AREA OF CIRCLE IS:", AREA;
END PROGRAM
