PROGRAM AreaOfRectangle
    IMPLICIT NONE
    REAL::A,B,AREA
    PRINT*,"ENTER THE VALUE OF HEIGHT(a):"
    READ*,A
    PRINT*,"ENTER THE VALUE OF WIDTH(b):"
    READ*,B
    AREA=(A*B)
    PRINT*,"THE AREA OF THE RECTANGLE IS:",AREA
END PROGRAM
