PROGRAM DiagonalOfRectangle
    IMPLICIT NONE
    REAL::A,B,D
    PRINT*,"ENTER THE VALUE OF HEIGHT(a):"
    READ*,A
    PRINT*,"ENTER THE VALUE OF WIDTH(b):"
    READ*,B
    D=SQRT(A**2+B**2)
    PRINT*,"THE LENGTH OF THE DIAGONAL OF THE RECTANGLE IS:",D
END PROGRAM
