PROGRAM PerimeterOfRectangle
    IMPLICIT NONE
    REAL::A,B,p
    PRINT*,"ENTER THE VALUE OF HEIGHT(a):"
    READ*,A
    PRINT*,"ENTER THE VALUE OF WIDTH(b):"
    READ*,B
    p=2*(A+B)
    PRINT*,"THE PERIMETER OF THE RECTANGLE IS:",P
END PROGRAM
