PROGRAM volumeOfCylinder
    IMPLICIT NONE
    REAL::PHI,R,H,VOLUME
    PHI=3.1416
    PRINT*,"ENTER THE VALUE OF RADIUS(r):"
    READ*,R
    PRINT*,"ENTER THE VALUE OF HEIGHT(h):"
    READ*,H
    VOLUME=PHI*R**2*h
    PRINT*,"THE VOLUME OF CYLINDER IS:", VOLUME
END PROGRAM
